### ISSUE TITLE
Exclude Some Files

### ISSUE THREAD

**Issue by hasimyerlikaya** [normidar/auto_exporter#1]
Hi,

I need to exclude some files from export.dart
Is there any annotation for that?

**Comment by normidar** [comment]
@hasimyerlikaya 
There is no such feature yet, I will try to implement it.

Thanks for advice.

**Comment by normidar** [comment]
@hasimyerlikaya 
I implemented this feature and I will add it to the next version(v1.5.0).

Thanks again for your advice.

**Comment by hasimyerlikaya** [comment]
@normidar Thank you, It will be very useful.
